version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/GSA/aws-account-broker

    steps:
      - checkout

      - run:
          name: Install dep from source
          command: go get -u github.com/golang/dep/cmd/dep

      - run:
          name: Install dependencies
          command: dep ensure

      - run:
          name: Run go vet to check for likely mistakes in packages
          command: go vet

      - run:
          name: Install goLint
          command: |
            go get -u golang.org/x/lint/golint
            go get -u github.com/GeertJohan/fgt

      # Using fgt to run golint causes the build to fail if any lint is found. 
      # Otherwise, golint always returns a 0 result.
      - run:
          name: Lint checks
          command: fgt golint

      - run:
          name: Run go test
          command: go test

      - run:
          name: Build
          command: go build
